data:
  train_path: data/samsum-train.csv
  test_path: data/samsum-test.csv
  val_path: data/samsum-validation.csv

model:
  checkpoint: sshleifer/distilbart-cnn-12-6
  output_dir: bart_samsum

training:
  seed: 42
  learning_rate: 2e-5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 2
  weight_decay: 0.01
  num_train_epochs: 4
  predict_with_generate: true
  fp16: true
  report_to: none
