device: "cuda"  # Use "cpu" if GPU is not available

models:
  t5_summary_model: "t5-base"
  t5_question_model: "ramsrigouthamg/t5_squad_v1"
  sense2vec_model: "s2v_old"
  sentence_transformer_model: "msmarco-distilbert-base-v3"

summarizer:
  max_len: 512
  num_beams: 3
  min_length: 75
  max_length: 300

question_generator:
  max_len: 384
  num_beams: 5
  max_length: 72

distractors:
  top_n: 10
  lambda: 0.6
